// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsV1jkhfXq5pbndSDNkTdzvZTuYh_5BY',
    appId: '1:312131039668:web:e81c4bcbf5ecb055a982e1',
    messagingSenderId: '312131039668',
    projectId: 'kajian-fikih',
    authDomain: 'kajian-fikih.firebaseapp.com',
    storageBucket: 'kajian-fikih.appspot.com',
    measurementId: 'G-G74920YKE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldZu4gNsfzl_GGjQ5m-a83Ri6yW-hOQU',
    appId: '1:312131039668:android:a7ac9549b3d2a75ea982e1',
    messagingSenderId: '312131039668',
    projectId: 'kajian-fikih',
    storageBucket: 'kajian-fikih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ZSZxVuWFIXOqYhQgFVlhtFbEDE3y_8Q',
    appId: '1:312131039668:ios:b1ae65f5137020a9a982e1',
    messagingSenderId: '312131039668',
    projectId: 'kajian-fikih',
    storageBucket: 'kajian-fikih.appspot.com',
    iosBundleId: 'com.example.kajianFikih',
  );
}
